# server
SERVICE_NAME: "tw-media-analytics-service"
ENV: dev # local, dev, prod

# ai
GEMINI_API_KEY: 

# GCP
GCP_PROJECT_ID: 

# MYSQL
MYSQL_URL_SUFFIX: 
MYSQL_DB_ACCOUNT: 
MYSQL_DB_PASSWORD: 
MYSQL_DB_HOST: 
MYSQL_DB_PORT: 
MYSQL_DB_NAME:

# OTEL
OTEL_EXPORTER_OTLP_HOST: 
OTEL_EXPORTER_OTLP_PORT: 4317
OTEL_BATCH_TIMEOUT: 5 # 5s
OTEL_BATCH_SIZE: 512 # 512